name: Deploy Express JS Elevate

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH Connection
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
          set -e

          # Navigate to the project directory
          cd ${{ secrets.VPS_DEPLOY_PATH }} || { echo "Project folder not found!"; exit 1; }

          # Pull the latest code
          git reset --hard HEAD
          git clean -fd
          git pull origin main

          # Create the .env file from GitHub Secret
          echo "${{ secrets.ENV }}" > .env
          chmod 600 .env  # Secure the .env file
          
          # Build the application
          rm -rf node_modules package-lock.json

          # Install dependencies
          npm install

          npm rebuild bcrypt --update-binary

          # Restart the application using PM2
          pm2 restart elevate_be || pm2 start npm -- start --name elevate_be

          # Save PM2 state
          pm2 save

          echo "Deployment completed successfully!"
          EOF
          
